package pl.mirbudpol.sklepbudowlany;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import pl.mirbudpol.sklepbudowlany.Entity.Klient;
import pl.mirbudpol.sklepbudowlany.accessingdatamysql.KlientRepository;

@RestController
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class HelloController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private KlientRepository klientRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Klient n = new Klient();
        n.setImie(name);
        n.setEmail(email);
        klientRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Klient> getAllUsers() {
        // This returns a JSON or XML with the users
        return klientRepository.findAll();
    }
}
